export const data = [
    "Filtr oleju",
    "Filtr powietrza",
    "Filtr paliwa",
    "Filtr kabinowy",
    "Klocki hamulcowe przód",
    "Klocki hamulcowe tył",
    "Tarcze hamulcowe przód",
    "Tarcze hamulcowe tył",
    "Amortyzator przedni",
    "Amortyzator tylny",
    "Sprężyna zawieszenia",
    "Wahacz przedni",
    "Końcówka drążka kierowniczego",
    "Półoś napędowa",
    "Chłodnica wody",
    "Chłodnica klimatyzacji",
    "Pompa wody",
    "Pasek rozrządu",
    "Napinacz paska rozrządu",
    "Pasek wielorowkowy",
    "Napinacz paska wielorowkowego",
    "Świeca zapłonowa",
    "Cewka zapłonowa",
    "Akumulator",
    "Alternator",
    "Rozrusznik",
    "Sonda lambda",
    "Przepływomierz powietrza",
    "Czujnik ABS",
    "Łożysko koła przednie",
    "Łożysko koła tylne",
];